name: Publish

on:
  pull_request_target:
    types:
      - closed
    paths:
      - .release_notes/**

jobs:
  gh_release:
    if: github.event.pull_request.merged == true
    uses: taskany-inc/release/.github/workflows/gh_release.yml@main
    secrets: inherit
  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Version
        id: version
        run: |
          echo "version<<EOF" >> $GITHUB_OUTPUT
          echo "$(cat version)" >> $GITHUB_OUTPUT
          echo EOF >> $GITHUB_OUTPUT
      - name: Build and Push — Default
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: taskany/issues:latest,taskany/issues:${{ steps.version.outputs.version }}
      - name: Build and Push — Enterprise
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.enterprise
          push: true
          tags: taskany/issues-enterprise:latest,taskany/issues-enterprise:${{ steps.version.outputs.version }}

